/**:
  ros__parameters:
    offboard:
      controller:
        roll: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        pitch: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        frequency_hertz: 50.0
        motor_thrust_percentage: 0.1
      px4_ros2_message_mapping:
        input: 
          attitude: false
          angular_rate: false
        output:
          servos: true
          motors: false
      mission:
          setpoint:
            radians: 0.0

