/**:
  ros__parameters:
    offboard:
      mass_of_system: 1.584
      length_of_pendulum: 0.2
      gravitational_acceleration: 9.81
      moment_of_inertia: 0.0375
      vehicle: 
        servo_active: true
        motor_active: true
        servo_max_tilt_angle_degrees: 30.
        default_motor_pwm: 0.50 # active when position controllers are off
        motor_max_pwm: 0.75
        motor_thrust_curve: # newtons = (pwm * m + b) / 1000 * g;
          m: 2696.6
          b: -38.95
      controller:
        attitude: 
          active: [true, true, true]
          frequency_hertz: 50.
          gains:
            k_p: [0.50, 0.70, 0.40]
            k_d: [0.30, 0.40, 0.20]
            k_i: [0.00, 0.00, 0.10]
        position: 
          active: true
          gains:
            k_p:  [4.0, 4.0, 5.5]   # Proportional gain
            k_d:  [3.0, 3.0, 3.0]   # Derivative gain
            k_i:  [0., 0., 0.2]     # Integral gain
            k_ff: [1.0, 1.0, 1.0]   # Feedforward gain
            min_output: [-20., -20., -20.] # Minimum output of each PID
            max_output: [ 20.,  20.,  20.]
        frequency_hertz: 50.
      mission:
        trajectory_setpoint:
          active: false
