/**:
  ros__parameters:
    offboard:
      controller:
        roll: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        pitch: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        time_step_seconds: 0.02 # 50 Hz
        motor_thrust_percentage: 0.1
      px4_ros2_message_mapping:
        input:
          attitude: true
          angular_rate: true
        output:
          servos: true
          motors: false
      mission:
          setpoint:
            radians: 0.0
