/**:
  ros__parameters:
    offboard:
      mass_of_system: 1.584
      length_of_pendulum: 0.2
      gravitational_acceleration: 9.81
      moment_of_inertia: 0.0375
      vehicle: 
        servo_active: true
        motor_active: true
        servo_max_tilt_angle_degrees: 30.
        default_motor_pwm: 0.50 # active when position controllers are off
        motor_max_pwm: 0.75
        motor_thrust_curve: # newtons = (pwm * m + b) / 1000 * g;
          m: 2696.6
          b: -38.95
      controller:
        roll: 
          active: true
          gains:
            k_p: 0.5
            k_d: 0.3
            k_i: .0
        pitch: 
          active: true
          gains:
            k_p: 0.7
            k_d: 0.4
            k_i: .0
        yaw: 
          active: true
          gains:
            k_p: 0.40
            k_d: 0.2
            k_i: 0.1
        position: 
          active: true
          gains:
            k_p: [4.0, 4.0, 5.5]   # Proportional gain
            k_d: [3.0, 3.0, 3.0]   # Derivative gain
            k_i: [0., 0., 0.2]     # Integral gain
            min_output: [-20., -20., -20.] # Minimum output of each PID
            max_output: [ 20.,  20.,  20.]
        frequency_hertz: 50.
      mission:
        trajectory_setpoint:
          active: false
        sine_wave_trajectory: 
          period: 5.

          amplitude_attitude_degrees: 30.
          activate_attitude_roll:  false
          activate_attitude_pitch: false
          activate_attitude_yaw:   false

          amplitude_position_meters: 1.
          activate_position_x: false
          activate_position_y: false
          activate_position_z: false
