/**:
  ros__parameters:
    offboard:
      mass_of_system: 1.5
      length_of_pendulum: 0.2
      gravitational_acceleration: 9.81
      moment_of_inertia: 0.375
      vehicle:
        servo_active: false
        motor_active: false
        servo_max_tilt_angle_degrees: 30.
        default_motor_pwm: 0.45 # active when position controllers are off
        motor_max_pwm: 0.8
        motor_thrust_curve: # newtons = (pwm * m + b) / 1000 * g;
          m: 2696.6
          b: -38.95
      controller:
        attitude:
          active: [true, true, true]
          frequency_hertz: 50.
          gains:
            k_p: [0.3350, 0.3350, 0.3350]
            k_d: [0.1616, 0.1616, 0.1616]
            k_i: [0.3162, 0.3162, 0.3162]
        position: 
          active: true
          frequency_hertz: 50.
          gains:
            k_p: [8.0, 8.0, 8.0]   # Proportional gain
            k_d: [3.0, 3.0, 3.0]   # Derivative gain
            k_i: [0.2, 0.2, 0.1]   # Integral gain
            min_output: [-20., -20., -20.] # Minimum output of each PID
            max_output: [ 20.,  20.,  20.]
      mission:
        trajectory_setpoint:
          active: true
