/**:
  ros__parameters:
    offboard:
      mass_of_system: 1.5
      length_of_pendulum: 0.2
      gravitational_acceleration: 9.81
      moment_of_inertia: 0.375
      controller:
        roll: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        pitch: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        yaw: 
          active: true
          gains:
            k_p: 0.3350
            k_d: 0.1616
            k_i: 0.3162
        frequency_hertz: 50.
        default_motor_pwm: 0.45
        servo_max_tilt_angle_degrees: 30.
        motor_max_pwm: 0.8
        motor_thrust_curve: # newtons = (pwm * m + b) / 1000 * g;
          m: 2696.6
          b: -38.95
      mission:
        sine_wave_trajectory: 
          period: 5.

          amplitude_attitude_degrees: 30.
          activate_attitude_roll:  false
          activate_attitude_pitch: false
          activate_attitude_yaw:   false

          amplitude_position_meters: 1.
          activate_position_x: false
          activate_position_y: false
          activate_position_z: false
